name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Copy WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
 # Path to your built war file
         source: "target/*.war"
 # Path where Tomcat looks for apps (usually /var/lib/tomcat/webapps)
         target: "/home/ec2-user/deploy-temp"
 strip_components
        
      - name: Copy Website Files to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/ec2_key.pem" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/static-site/

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            # Install Apache HTTP Server
            sudo yum install -y httpd

            # Start and Enable Apache
            sudo systemctl enable httpd
            sudo systemctl start httpd

            # Clean existing document root
            sudo rm -rf /var/www/html/*

            # Copy new website files
            sudo cp -r /tmp/static-site/* /var/www/html/

            # Set permissions
            sudo chown -R apache:apache /var/www/html
            sudo chmod -R 755 /var/www/html

            # Restart Apache
            sudo systemctl restart httpd

          EOF
